on: push

env:
  UPDATE_GUTENBERG_PR_GITHUB_TOKEN: ${{ secrets.UPDATE_GUTENBERG_PR_GITHUB_TOKEN }}

jobs:
  update-oguzkocer-test-versin-bin-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: run
